import React from "react";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Hafez Design Studio",
  description: "Generated by create next app",
};

const CommercialProjects: React.FC = () => {
  return <div>Commercial Projects</div>;
};

export default CommercialProjects;
