// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for Company Information documents
 */
interface CompanyInformationDocumentData {
  /**
   * Company Name field in *Company Information*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Contoso.com
   * - **API ID Path**: company_information.company_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  company_name: prismic.KeyTextField;

  /**
   * Company Logo field in *Company Information*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: company_information.company_logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  company_logo: prismic.ImageField<never>;

  /**
   * Address Line 1 field in *Company Information*
   *
   * - **Field Type**: Text
   * - **Placeholder**: 123 some street
   * - **API ID Path**: company_information.address_line_1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  address_line_1: prismic.KeyTextField;

  /**
   * Address Line 2 field in *Company Information*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Suite xyz
   * - **API ID Path**: company_information.address_line_2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  address_line_2: prismic.KeyTextField;

  /**
   * Company City field in *Company Information*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Lowell
   * - **API ID Path**: company_information.company_city
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  company_city: prismic.KeyTextField;

  /**
   * Company State field in *Company Information*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Massachusetts
   * - **API ID Path**: company_information.company_state
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  company_state: prismic.KeyTextField;

  /**
   * Company Country field in *Company Information*
   *
   * - **Field Type**: Text
   * - **Placeholder**: US
   * - **API ID Path**: company_information.company_country
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  company_country: prismic.KeyTextField;

  /**
   * Company Website URL field in *Company Information*
   *
   * - **Field Type**: Link
   * - **Placeholder**: https://contoso.com
   * - **API ID Path**: company_information.company_website_url
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  company_website_url: prismic.LinkField;
}

/**
 * Company Information document from Prismic
 *
 * - **API ID**: `company_information`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CompanyInformationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<CompanyInformationDocumentData>,
    "company_information",
    Lang
  >;

type StaticPageDocumentDataSlicesSlice = never;

/**
 * Content for Static Page documents
 */
interface StaticPageDocumentData {
  /**
   * Page Title field in *Static Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: ie: Home
   * - **API ID Path**: static_page.page_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  page_title: prismic.KeyTextField;

  /**
   * Page Description field in *Static Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: This is the homepage
   * - **API ID Path**: static_page.page_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  page_description: prismic.KeyTextField;

  /**
   * Page Keywords field in *Static Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: websites, marketing, search engine optimization,...
   * - **API ID Path**: static_page.page_keywords
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  page_keywords: prismic.KeyTextField;

  /**
   * Slice Zone field in *Static Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: static_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<StaticPageDocumentDataSlicesSlice> /**
   * Meta Title field in *Static Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: static_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Static Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: static_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Static Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: static_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Static Page document from Prismic
 *
 * - **API ID**: `static_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type StaticPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<StaticPageDocumentData>,
    "static_page",
    Lang
  >;

export type AllDocumentTypes = CompanyInformationDocument | StaticPageDocument;

/**
 * Primary content in *TextBlock → Default → Primary*
 */
export interface TextBlockSliceDefaultPrimary {
  /**
   * name field in *TextBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.default.primary.name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;
}

/**
 * Default variation for TextBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TextBlock*
 */
type TextBlockSliceVariation = TextBlockSliceDefault;

/**
 * TextBlock Shared Slice
 *
 * - **API ID**: `text_block`
 * - **Description**: TextBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextBlockSlice = prismic.SharedSlice<
  "text_block",
  TextBlockSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      CompanyInformationDocument,
      CompanyInformationDocumentData,
      StaticPageDocument,
      StaticPageDocumentData,
      StaticPageDocumentDataSlicesSlice,
      AllDocumentTypes,
      TextBlockSlice,
      TextBlockSliceDefaultPrimary,
      TextBlockSliceVariation,
      TextBlockSliceDefault,
    };
  }
}
