import React from "react";
import type { Metadata } from "next";
import Image from "next/image";
//import Feed from "@/components/ui/Feed";

export const metadata: Metadata = {
  title: "Hafez Design Studio | About us",
  description: "Generated by create next app",
};

const AboutPage: React.FC = () => {
  return (
    <>
      <div className="w-screen pt-[200px] pb-[220px]">
        <div className="container mx-auto flex flex-col gap-2 lg:flex-row-reverse lg:gap-0">
          <div className="w-full flex flex-col gap-y-6 lg:w-1/2">
            <div className="w-full h-full pb-4">
              <Image
                src="/ehab.png"
                alt="Founder of Sansa Interiors in Toronto"
                className="object-cover h-full w-full"
                width={1500}
                height={1000}
              />
            </div>
          </div>
          <div className="w-full flex flex-col justify-center items-start gap-2 px-6 lg:w-1/2">
            {/* <h2 className="text-2xl font-black mb-2">Meet Your Team</h2> */}
            <h3 className="text-3xl font-black">Ihab Hafez</h3>
            <h4 className="text-lg font-semibold mb-4">
              Founder &amp; Principal Designer
            </h4>
            <p className="text-lg text-justify mb-2">
              Ihab Hafez, founder of Hafez Design Studio, combines a global
              perspective with a passion for creating timeless, modern spaces
              that blend function and style. With a bachelor&apos;s degree in
              interior design from Egypt and nearly a decade teaching Art &
              Design in Kuwait, he developed a detail-oriented approach rooted
              in creativity and empathy. His journey continued in Canada, where
              he earned recognition like the Staples Business Advantage
              Scholarship and gained valuable experience through internships in
              residential and commercial design
            </p>
            <p className="hidden text-lg text-justify mb-2 lg:block">
              At Hafez Design Studio, Ihab transforms spaces into functional
              works of art, whether it&apos;s a sleek kitchen renovation, custom
              millwork, or comprehensive interior design. Drawing inspiration
              from travel and modern aesthetics, his designs prioritize quality,
              innovation, and a personalized touch, ensuring every project
              exceeds client expectations.
            </p>
          </div>
        </div>
        <div className="container mx-auto">
          <div className="w-full flex flex-col justify-center items-start">
            <h2 className="text-3xl font-semibold mb-4">
              Designer Credentials &amp; Awards
            </h2>
            <p className="w-[90%] mb-8">
              At Hafez Design Studio, Principal Designer Ihab N. Hafez is deeply
              committed to continuous learning as a cornerstone of delivering
              exceptional design solutions. We stay at the forefront of industry
              trends and innovations by reading books and engaging in
              professional development opportunities. This dedication to growth
              allows us to craft functional timeless, sophisticated, and modern
              spaces that meet the unique needs of our clients while exceeding
              expectations
            </p>
            <div className="flex flex-col gap-4 lg:flex-row lg:pl-6">
              <Image
                src="/nkb-cert.png"
                alt="Founder of Sansa Interiors in Toronto"
                className="object-cover border shadow-lg"
                width={400}
                height={300}
              />
              <Image
                src="/cert.png"
                alt="Founder of Sansa Interiors in Toronto"
                className="object-cover border shadow-lg"
                width={400}
                height={300}
              />
              <Image
                src="/nkb-cert-02.png"
                alt="Founder of Sansa Interiors in Toronto"
                className="object-cover border shadow-lg"
                width={400}
                height={300}
              />
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default AboutPage;
