import React from "react";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Hafez Design Studio | About us",
  description: "Generated by create next app",
};

const AboutPage: React.FC = () => {
  return <div>About page</div>;
};

export default AboutPage;
