import React from "react";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Hafez Design Studio",
  description: "Generated by create next app",
};

const ResidentialProjects: React.FC = () => {
  return <div>Residential Projects</div>;
};

export default ResidentialProjects;
