import React from "react";
import type { Metadata } from "next";
import FeaturedServices2 from "@/components/ui/FeaturedServices2";

export const metadata: Metadata = {
  title: "Designer Services",
  description: "Generated by create next app",
};

const ResidentialServices: React.FC = () => {
  return (
    <>
      {/*  */}
      <FeaturedServices2 />
    </>
  );
};

export default ResidentialServices;
