import React from "react";
import type { Metadata } from "next";
import FeaturedServices from "@/components/ui/FeaturedServices3";
import AccordionProcess from "@/components/ui/AccordionProcess";

export const metadata: Metadata = {
  title: "Residential Services!!",
  description: "Generated by create next app",
};

const CommercialServices: React.FC = () => {
  return (
    <>
      <FeaturedServices
        serviceTitle=""
        serviceName="Commercial Design Services"
        serviceDescription="Elevate your business with Hafez Design Studio's innovative and functional designs. Whether you need custom millwork to increase storage and eliminate clutter, a professional background for Zoom meetings or video shoots, or a complete office redesign, we’re here to help. From feasibility studies that inform your next investment to creating a workplace that fosters collaboration, focus, and a welcoming environment for your team, we ensure every detail aligns with your brand and vision. Let us transform your commercial space into a tool for productivity and success."
        serviceDescription2=""
      />
      <div className="container max-w-[70%] mx-auto">
        <h2 className="text-4xl font-black italic mb-6">Our Design Process.</h2>
        <p className="text-gray-800 pr-[12vw]">
          At Hafez Design Studio, we pride ourselves on maintaining a
          collaborative and transparent process from start to finish. As a
          boutique interior design studio, we prioritize personalized attention
          and constant communication with our clients. Before starting any new
          project phase, we schedule dedicated meetings to review progress,
          discuss upcoming steps, and ensure alignment with your vision. We
          believe it&apos;s essential not only to keep you informed about where
          we are in your investment process but also to ensure you feel
          confident, comfortable, and excited about the outcome. Our commitment
          is to design spaces that you&apos;ll love, delivering results that
          meet and exceed your expectations. Together, we&apos;ll create a space
          that reflects your style, values, and aspirations.
        </p>
        <div className="w-full flex flex-col items-start text-left">
          <AccordionProcess />
        </div>
      </div>
    </>
  );
};

export default CommercialServices;
