import React from "react";
import type { Metadata } from "next";
import FeaturedServices from "@/components/ui/FeaturedServices";
import AccordionProcess from "@/components/ui/AccordionProcess";

export const metadata: Metadata = {
  title: "Residential Services!!",
  description: "Generated by create next app",
};

const ResidentialServices: React.FC = () => {
  return (
    <>
      <FeaturedServices />
      <div className="container mx-aut0">
        <h2 className="text-4xl font-black italic mb-6">Our Design Process.</h2>
        <p className="text-gray-800 pr-[12vw]">
          At Hafez Design Studio, we pride ourselves on maintaining a
          collaborative and transparent process from start to finish. As a
          boutique interior design studio, we prioritize personalized attention
          and constant communication with our clients. Before starting any new
          project phase, we schedule dedicated meetings to review progress,
          discuss upcoming steps, and ensure alignment with your vision. We
          believe it&apos;s essential not only to keep you informed about where
          we are in your investment process but also to ensure you feel
          confident, comfortable, and excited about the outcome. Our commitment
          is to design spaces that you&apos;ll love, delivering results that
          meet and exceed your expectations. Together, we&apos;ll create a space
          that reflects your style, values, and aspirations.
        </p>
        <AccordionProcess />
      </div>
    </>
  );
};

export default ResidentialServices;
