import React from "react";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Hafez Design Studio",
  description: "Generated by create next app",
};

const ResidentialServices: React.FC = () => {
  return <div>Residential Services</div>;
};

export default ResidentialServices;
